-- '=' OPERATOR
-- RETRIEVE ALL CUSTOMERS FROM GERMANY

SELECT *
FROM customers
WHERE country = 'GERMANY'

-- '<>' NOT EQUAL TO OPERATOR
-- RETRIEVE ALL CUSTOMERS WHO ARE NOT FROM GERMANY

SELECT * 
FROM customers
WHERE country <> 'GERMANY'


-- '>' GREATER THAN OPERATOR
-- RETRIVE ALL CUSTOMERS WITH A SCORE > 300

SELECT * 
FROM customers
WHERE score > 300


-- '>=' GREATER THAN OR EQUAL TO OPERATOR
-- RETRIVE ALL CUSTOMERS WITH A SCORE > 300 OR MORE

SELECT * 
FROM customers
WHERE score >= 300



-- '<' GREATER THAN OPERATOR
-- RETRIVE ALL CUSTOMERS WITH A SCORE < 300

SELECT * 
FROM customers
WHERE score < 300


-- '<=' GREATER THAN OR EQUAL TO OPERATOR
-- RETRIVE ALL CUSTOMERS WITH A SCORE < 300 OR MORE

SELECT * 
FROM customers
WHERE score <= 300






