-- COMBINES EVERY ROWS FROM LEFT WITH EVERY ROWS FROM RIGHT ALL POSSIBLE COMBINARIONS 

-- GENERATE ALL POSSIBLE COMBINATIONS OF CUSTOMERS AND ORDERS

-- HOW TO CHOOSE BETWEEN JOIN TYPES

SELECT *
FROM customers
CROSS JOIN orders

SELECT *
FROM customers

SELECT *
FROM orders