-- [CREATE]

-- CREATE A NEW TABLE CALLED PERSONS WITH COLUMNS: ID, PERSON_NAME, BIRTH_DATE AND PHONE

CREATE TABLE persons2 (
	id INT NOT NULL,
	person_name VARCHAR(50) NOT NULL,
	birth_date DATE,
	phone VARCHAR(15) NOT NULL,
	CONSTRAINT pk_persons PRIMARY KEY (id)

)

SELECT * 
FROM persons2


-- [ALTER (ADD)]

-- ADD A NEW COLUMN CALLED EMAIL TO THE PERSONS2 TABLE

ALTER TABLE persons2
ADD email VARCHAR(20) NOT NULL


-- [ALTER (DROP COLUMN)]

-- REMOVE THE COLUMN PHONE FROM THE PERSONS2 TABLE 

ALTER TABLE persons2
DROP COLUMN phone


-- [DROP]

-- DELETE THE TABLE PERSONS2 FROM THE DATABASE

DROP TABLE persons2