-- FULL ANTI JOIN
-- RETURN ONLY ROWS THAT DON'T MATCH IN EITHER TABLES

-- FIND CUSTOMERS WITHOUT ORDERS AND ORDERS WITHOUT CUSTOMERS

SELECT *
FROM customers AS C
FULL JOIN orders AS O
ON C.id = O.customer_id
WHERE C.id IS NULL OR O.customer_id IS NULL

SELECT *
FROM customers

SELECT *
FROM orders