-- FIND THE TOTAL SCORE FOR EACH COUNTRY

SELECT country, SUM(score) AS [TOTAL SCORE]
FROM customers
GROUP BY country



-- FIND THE TOTAL SCORE AND TOTAL NUMBER OF CUSTOMERS FOR EACH COUNTRY

SELECT country, COUNT(first_name) AS [TOTAL CUSTOMERS], SUM(score) AS [TOTAL SCORE]
FROM customers
GROUP BY country
