/*  FIND THE AVERAGE SCORE FOR EACH COUNTRY
	COUNSIDERING ONLY CUSTOMERS WITH A SCORE NOT EQUAL TO 0 
	AND RETURN ONLY THOSE COUNTRIES WITH AN AVERAGE SCORE GREATER THAN 430
*/

SELECT country, AVG(score) AS [TOTAL SCORE]
FROM customers
WHERE score  <> 0
GROUP BY country
HAVING AVG(score) >= 425

SELECT * FROM customers