-- RETURN ALL ROWS FROM LEFT TEABLE AND ONLY MATCHING FROM RIGHT TABLE

-- GET ALL CUSTOMERS ALONG WITH THEIR ORDES INCLUDING THOSE WITHOUT ORDERS

SELECT 
	C.id,
	C.first_name,
	O.order_id,
	O.sales

FROM customers AS C
LEFT JOIN orders AS O
ON C.id = O.customer_id
