-- AND OPERATORS
-- RETRIEVE ALL CUSTOMERS WHO ARE FROM THE GERMANY AND HAVE A SCORE > 500

SELECT * 
FROM customers
WHERE country = 'GERMANY' AND score > 450


-- OR OPERATORS
-- RETRIEVE ALL CUSTOMERS WHO ARE EITHER FROM THE GERMANY OR HAVE A SCORE > 300

SELECT * 
FROM customers
WHERE country = 'GERMANY' OR score > 300



-- NOT OPERATORS
-- RETRIEVE ALL CUSTOMERS WITH A SCORE NOT < 500

SELECT * 
FROM customers
WHERE NOT score < 500
