-- IN OPERATOR
-- RETIRIEVE ALL CUSTOMERS FROM EITHER GERMANY OR USA

SELECT * 
FROM customers
WHERE country IN ('GERMANY', 'USA')


-- NOT IN OPERATOR
-- RETIRIEVE ALL CUSTOMERS THOSE ARE NOT FROM EITHER GERMANY OR USA

SELECT *
FROM customers
WHERE country NOT IN ('GERMANY', 'USA')
