-- RIGHT ANTI JOIN
-- RETURN ROWS FROM RIGHT THAT HAS NO MATCH IN LEFT

-- GET ALL ORDERS WITHOUT MATCHING CUSTOMERS

SELECT 
	C.id,
	C.first_name,
	O.order_id,
	O.sales
FROM customers AS C
RIGHT JOIN orders AS O
ON C.id = O.customer_id
WHERE C.id IS NULL


-- GET ALL ORDERS WITHOUT MATCHING CUSTOMERS

SELECT *
FROM orders AS O
LEFT JOIN customers AS C
ON C.id = O.customer_id
WHERE C.id IS NULL