-- LIKE OPERATOR
-- FIND ALL CUSTOMERS WHOSE FIRST NAME STARTS WITH 'M' (_%)

SELECT *
FROM customers
WHERE first_name LIKE 'M%'


-- FIND ALL CUSTOMERS WHOSE FIRST NAME ENDS WITH 'N' (%_)

SELECT *
FROM customers
WHERE first_name LIKE '%N'


-- FIND ALL CUSTOMERS WHOSE FIRST NAME CONTAINS 'R' (_%_)

SELECT *
FROM customers
WHERE first_name LIKE '%R%' 


-- FIND ALL CUSTOMERS WHOSE FIRST NAME HAS 'R' IN THE 3RD POSITION (__%)

SELECT *
FROM customers
WHERE first_name LIKE '__R%'