-- UNION ALL

-- COMBINE THE DATA FROM EMPLOYEES AND CUSTOMRES INTO ONE TABLE, INCLUDING DUPLICATES

SELECT 
	FirstName,
	LastName
FROM Sales.Employees
UNION ALL
SELECT 
	FirstName,
	LastName
FROM Sales.Customers



-- EXCEPT
-- RETURN ALL DISTINCT ROWS FROM THE FIRST QUERY THAT ARE NOT FOUND IN THE SECOND QUERY

-- FIND THE EMPLOYEES WHO ARE NOT THE CUSTOMERS AT THE SAME TIME

SELECT 
	FirstName,
	LastName
FROM Sales.Employees
EXCEPT
SELECT
	FirstName,
	LastName
FROM Sales.Customers



--  INTERSECT
-- RETURN ONLY THE ROWS THAT ARE COMMON IN BOTH QUERIES 

-- FIND THE EMPLOYEES WHO ARE ALSO CUSTOMERS

SELECT 
	FirstName,
	LastName
FROM Sales.Employees
INTERSECT
SELECT
	FirstName,
	LastName
FROM Sales.Customers

