-- SQL FUNCTIONS
-- A BUILT IN SQL CODE; ACCEPT AN INPUT VALUE, PROCESS IT, RETURN AN OUTPUT VALUE

-- STRING FUNCTIONS

-- CONCAT FUNCTION

-- SHOW A LIST OF CUSTOMERS FIRST NAME TOGETHER WITH THEIR COUNTRY IN ONE COLUMNS

SELECT 
first_name,
country,
CONCAT(first_name, ' ', country) AS name_country
FROM customers




-- LOWER CASE FUNCTION
-- CONVERT THE FIRST NAME TO LOWER CASE

SELECT
	LOWER(FIRST_NAME),
	COUNTRY
FROM customers


-- UPPER CASE FUNCTION
-- CONVERT THE FIRST NAME TO UPPER CASE

SELECT
	UPPER(FIRST_NAME),
	COUNTRY
FROM customers


-- TRIM FUNCTION (REMOVE LEADING AND TRAILING SPACES)
-- FIND CUSTOMERS WHOSE FIRST NAME CONTAINS LEADING OR TRAILING SPACE


SELECT
	UPPER(FIRST_NAME),
	COUNTRY
FROM customers
WHERE first_name <> TRIM(FIRST_NAME)



-- REPLACE FUNCTION (REPLACE SPECIFIC CHARACTERS WITH A NEW CHARACTER)
-- REMOVE DASHES __ FROM A PHONE NUMBER

SELECT
	'234-321-6655' AS PHONE_NUMBER,
REPLACE('234-321-6655', '-', '/') AS CLEAN_PHONE



-- LEN FUNCTION (COUNT HOW MANY CHARACTERS)
-- CALCULATE THE LENGTH OF EACH CUSTOMERS FIRST NAME

SELECT 
	FIRST_NAME,
	LEN(FIRST_NAME) AS LENGTH
FROM customers


-- LEFT ( EXTRACT SPECIFIC NUMBER OF CHARACTERS FROM THE START)
-- RETRIEVE THE FIRST 2 CHARACTERS OF EACH FIRST NAME

SELECT 
	FIRST_NAME,
	LEFT(TRIM(FIRST_NAME), 2) AS LENGTH
FROM customers


-- RIGHT ( EXTRACT SPECIFIC NUMBER OF CHARACTERS FROM THE END)
-- RETRIEVE THE LAST 2 CHARACTERS OF EACH FIRST NAME

SELECT 
	FIRST_NAME,
	RIGHT(TRIM(FIRST_NAME), 2) AS LENGTH
FROM customers



-- SUBSTRING (EXTRACT A PART OF STRING AT A SPECIFIED POSITION)
-- RETRIVE A LIST OF CUSTOMERS FIRST NAMES AFTER REMOVING THE FIRST CHARACTERS

SELECT 
	FIRST_NAME,
	SUBSTRING(TRIM(FIRST_NAME), 2, LEN(FIRST_NAME)) AS NAMES
FROM customers