-- RETRIEVE ONLY 3 CUSTOMERS

SELECT TOP 3 * FROM customers


-- RETRIEVE ONLY 3 CUSTOMERS WITH HIGHEST SCORE

SELECT TOP 3 * 
FROM customers
ORDER BY score DESC


-- RETRIEVE THE LOWEST 3 CUSTOMERS BASED ON THE SCORE

SELECT TOP 3 * 
FROM customers
WHERE score IS NOT NULL AND score > 0
ORDER BY score ASC


-- GET THE 2 MOST RECENT ORDERS

SELECT TOP 2 *
FROM orders
ORDER BY order_date DESC


-- STATIC VALUES

SELECT 123 AS STATIC_VALUE

SELECT 'HELLO' AS STATIC_STRING

SELECT id, FIRST_nAME, 'NEW_CUSTOMER' AS CUSTOMER_TYPE
FROM customers